on:
  create:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # Creation of version tags

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Crate publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo publish --dry-run --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
